--- 
title: "Data Analytics + Public Policy"
author: "Jeffrey Chen"
date: '`r Sys.Date()`'
output:
  html_document: default
  latex_engine: xelatex
  pdf_document: null
description: Manipulation - Mentality - Etiquette
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalikex
---

##Getting into the mentality

> __*Writing just any piece of code is easy. The challenging thing is to ensure that it works well and is repeatable.*__

To be successful in the wild requires the appropriate mindset and an embrace of data etiquette.  Data processing is not like a vampiric feeding frenzy of the sort that might be seen on Buffy the Vampire slayer (the TV show): one simply does not arbitrarily chomp at and slice data without any thought as to what comes next. It requires discipline and finesse to acquire a raw piece of information and extract the empirical substance. 

Hypothetically, imagine that you have conducted a three-month analytics project, rushing to obtain to a result. If asked to provide backup, documentation, and a process, it may very well require an additional few months to decipher your passionate but hasty explorations. Where did this data come from? Why did I take a dot product in this equation? What happened to the raw file? Who is Bob mentioned in this email?  Ultimately, the data scientist is in control and should be empowered to conduct data processing in a structured, scientific manner. _So, what exact does that mean?_ Here are five guidelines that make for successful, scalable data science projects:

- _Define a file structure and stick to it_. Create a folder for _scripts_ to store all code, another for _raw_ data, a folder for _outputs_ from data processing, and another for _documentation_. Choose any file structure, but make sure it is consistent and always followed.


- _Think modularly_.   One of the greatest human inventions is the assembly line. Each step in the process is discrete, requiring workers to specialize in one set of well-defined tasks. As a worker becomes specialized, production speed increases as workers focus on a repetitive task as opposed to switching between tasks. Also, if any step in the process needs to be improved, revised, or replaced, all other steps in the process are not disrupted -- only one step needs to be addressed. This standardization of processes is the only way to scale.  Coding is the same.  Each group of similar tasks can be rolled up into a function that is comprised of generic actions. For example, a function could transform involve downloading a file, unzipping it, loading into memory, and extract a specific set of fields, then saving out the extracted data. 

- _Adopt and stick to a coding style_. Each file, data field, and function should follow a style so that the logic is cohesive, readable and traceable. The [Google R Style Guide](https://google.github.io/styleguide/Rguide.xml), for example, sets easy to follow rules. For example, variable names should be labeled as lower case characters with  a `"."` as a separator:  `variable.name`. Functions should be named in proper case without spaces: `NewFunction` or `MyFunction`. Regardless of the style guide, file names should be meaningful and the only punctuation used should be `"_"` for spaces and `"."` to accompany the file type: `gdp_2014_10_02.json`. Be vigilent with your code style as it may be the difference between a successful and a failed project.


- _Work forward, not in circles_. Raw meats should never be placed with cooked meats. It's a one way street to keep things clean and sanitary. Data is also a one way street  Start from the raw data, make a copy when working with the raw, do thy bidding on the data, then output results or processed data as a new file. Never overwrite the raw file as this is the equivalent to repeatedly refridgerating and re-cooking already cooked meat -- the result may be less than desirable in the future. 


- _Version up_. Each time code is written, modified, amended, or updated, a new version should be saved. Saving can be done in one many ways. If on a local computer, simply adding a version number to the code file name would suffice with an entry to a log file. The log file can be as simple as a text file with time stamps indicating the date fo the edit, the file name and the nature of the edit. Services such as [Github](https://github.com/) are particularly useful for version control and working on code in groups. 

Following these basic guidelines is the difference between successful, scalable projects and ones that get stuck in the mud. 

## DIY
  